In [1]:
import numpy as np

a = np.random.randn(5) # rank 1 array - 5 guassian random numbers

In [2]:
print(a)

[-1.37582709 -0.72120331  0.7317325  -1.6444271   1.19146303]


In [3]:
print(a.shape) # rank 1 array -

(5,)


In [4]:
print(a.T)

[-1.37582709 -0.72120331  0.7317325  -1.6444271   1.19146303]


In [10]:
print(np.dot(a, a.T))

[[ 2.78967035  3.23866919  2.53602719 -3.41372669 -1.33880028]
 [ 3.23866919  3.75993462  2.94420204 -3.96316772 -1.55428086]
 [ 2.53602719  2.94420204  2.30544584 -3.10334291 -1.21707352]
 [-3.41372669 -3.96316772 -3.10334291  4.17738603  1.6382933 ]
 [-1.33880028 -1.55428086 -1.21707352  1.6382933   0.64250824]]


---

Matrix (Column Vector)

In [6]:
a = np.random.randn(5,1)

print(a) # column vector

[[ 1.67023063]
 [ 1.93905508]
 [ 1.51836947]
 [-2.04386546]
 [-0.80156612]]


In [7]:
print(a.T)

[[ 1.67023063  1.93905508  1.51836947 -2.04386546 -0.80156612]]


In [8]:
print(np.dot(a, a.T))

[[ 2.78967035  3.23866919  2.53602719 -3.41372669 -1.33880028]
 [ 3.23866919  3.75993462  2.94420204 -3.96316772 -1.55428086]
 [ 2.53602719  2.94420204  2.30544584 -3.10334291 -1.21707352]
 [-3.41372669 -3.96316772 -3.10334291  4.17738603  1.6382933 ]
 [-1.33880028 -1.55428086 -1.21707352  1.6382933   0.64250824]]


### Always use the column vector, row vector instead of rank 1 array data structure

for training AIs.

you can use assert(a.shape == 5.1) or a = a.reshape((5,1))

In [11]:
a = np.array([[1,1], [1,-1]])
b = np.array([[2], [3]])

c = a + b
print(c)

[[3 3]
 [4 2]]
